IF DB_ID(N'AshkanBankSphere') IS NULL CREATE DATABASE AshkanBankSphere;
GO
USE AshkanBankSphere;
GO
CREATE TABLE Users(Id INT IDENTITY PRIMARY KEY,Username NVARCHAR(100) NOT NULL UNIQUE,PasswordHash VARBINARY(32) NOT NULL,PasswordSalt VARBINARY(16) NOT NULL,IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Customers(Id INT IDENTITY PRIMARY KEY,FullName NVARCHAR(200) NOT NULL,NationalId NVARCHAR(30) NOT NULL UNIQUE,Phone NVARCHAR(30),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Accounts(Id INT IDENTITY PRIMARY KEY,CustomerId INT NOT NULL REFERENCES Customers(Id),AccountNumber NVARCHAR(34) NOT NULL UNIQUE,AccountType NVARCHAR(30) NOT NULL,Balance DECIMAL(19,4) NOT NULL DEFAULT 0 CHECK(Balance>=0),Currency NVARCHAR(3) NOT NULL DEFAULT 'IRR',Status NVARCHAR(20) NOT NULL DEFAULT 'Active' CHECK(Status IN('Active','Frozen','Closed')));
CREATE TABLE Transfers(Id BIGINT IDENTITY PRIMARY KEY,SourceAccountId INT NOT NULL REFERENCES Accounts(Id),TargetAccountId INT NOT NULL REFERENCES Accounts(Id),Amount DECIMAL(19,4) NOT NULL CHECK(Amount>0),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_Transfers_Different CHECK(SourceAccountId<>TargetAccountId));
GO
