using System.Data;using System.Security.Cryptography;using Microsoft.Data.SqlClient;
namespace AshkanBankSphere.Infrastructure;
public sealed class BankService {
 public bool Login(string username,string password){using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT PasswordHash,PasswordSalt,Role FROM Users WHERE Username=@u AND IsActive=1",c);cmd.Parameters.AddWithValue("@u",username);using var r=cmd.ExecuteReader();if(!r.Read())return false;var hash=(byte[])r[0];var salt=(byte[])r[1];var ok=CryptographicOperations.FixedTimeEquals(hash,Rfc2898DeriveBytes.Pbkdf2(password,salt,210000,HashAlgorithmName.SHA256,32));if(ok)BankSession.SignIn(username,r.GetString(2));return ok;}
 public DataTable Accounts(){using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT a.AccountNumber,a.AccountType,a.Balance,a.Currency,a.Status,c.FullName FROM Accounts a JOIN Customers c ON a.CustomerId=c.Id ORDER BY a.Id DESC",c);using var da=new SqlDataAdapter(cmd);var dt=new DataTable();da.Fill(dt);return dt;}
 public DataTable Customers(){using var c=BankDb.Open();using var da=new SqlDataAdapter("SELECT Id,FullName,NationalId,Phone,CreatedAt FROM Customers ORDER BY Id DESC",c);var dt=new DataTable();da.Fill(dt);return dt;}
 public void AddCustomer(string name,string nationalId,string phone){BankSession.RequireWrite();using var c=BankDb.Open();using var cmd=new SqlCommand("INSERT INTO Customers(FullName,NationalId,Phone) VALUES(@n,@id,@p)",c);cmd.Parameters.AddWithValue("@n",name);cmd.Parameters.AddWithValue("@id",nationalId);cmd.Parameters.AddWithValue("@p",phone);cmd.ExecuteNonQuery();}
 public void Transfer(string source,string target,decimal amount){BankSession.RequireWrite();if(amount<=0||source==target)throw new ArgumentException("Invalid transfer");using var c=BankDb.Open();using var tx=c.BeginTransaction(IsolationLevel.Serializable);try {using var cmd=new SqlCommand("SELECT Id,AccountNumber,Balance,Currency,Status FROM Accounts WITH(UPDLOCK,HOLDLOCK) WHERE AccountNumber IN (@s,@t)",c,tx);cmd.Parameters.AddWithValue("@s",source);cmd.Parameters.AddWithValue("@t",target);var dt=new DataTable();using(var r=cmd.ExecuteReader())dt.Load(r);if(dt.Rows.Count!=2)throw new InvalidOperationException("Account not found");var src=dt.AsEnumerable().Single(x=>x.Field<string>("AccountNumber")==source);var dst=dt.AsEnumerable().Single(x=>x.Field<string>("AccountNumber")==target);if(src.Field<string>("Status")!="Active"||dst.Field<string>("Status")!="Active")throw new InvalidOperationException("Inactive account");if(src.Field<string>("Currency")!=dst.Field<string>("Currency"))throw new InvalidOperationException("Currency mismatch");if(src.Field<decimal>("Balance")<amount)throw new InvalidOperationException("Insufficient funds");using var update=new SqlCommand("UPDATE Accounts SET Balance=Balance-@amount WHERE Id=@s;UPDATE Accounts SET Balance=Balance+@amount WHERE Id=@t;INSERT INTO Transfers(SourceAccountId,TargetAccountId,Amount) VALUES(@s,@t,@amount)",c,tx);update.Parameters.AddWithValue("@amount",amount);update.Parameters.AddWithValue("@s",src.Field<int>("Id"));update.Parameters.AddWithValue("@t",dst.Field<int>("Id"));update.ExecuteNonQuery();using var audit=new SqlCommand("INSERT INTO AuditEvents(EventType,Details) VALUES(@type,@details)",c,tx);
        audit.Parameters.Add("@type",SqlDbType.NVarChar,60).Value="Transfer";
        audit.Parameters.Add("@details",SqlDbType.NVarChar,1000).Value=$"{source} -> {target}; amount={amount.ToString(System.Globalization.CultureInfo.InvariantCulture)}";
        audit.ExecuteNonQuery();tx.Commit();}catch{tx.Rollback();throw;}}
 public DataTable Transfers(){using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT t.Id,s.AccountNumber AS SourceAccount,d.AccountNumber AS TargetAccount,t.Amount,t.CreatedAt FROM Transfers t JOIN Accounts s ON s.Id=t.SourceAccountId JOIN Accounts d ON d.Id=t.TargetAccountId ORDER BY t.Id DESC",c);using var da=new SqlDataAdapter(cmd);var dt=new DataTable();da.Fill(dt);return dt;}
 public (int customers,int accounts,int transfers,decimal balance) Summary(){using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT (SELECT COUNT(*) FROM Customers),(SELECT COUNT(*) FROM Accounts WHERE Status='Active'),(SELECT COUNT(*) FROM Transfers),(SELECT COALESCE(SUM(Balance),0) FROM Accounts WHERE Currency='IRR' AND Status<>'Closed')",c);using var r=cmd.ExecuteReader();r.Read();return (r.GetInt32(0),r.GetInt32(1),r.GetInt32(2),r.GetDecimal(3));}
 public void CreateAccount(int customerId,string number,string type){BankSession.RequireWrite();if(customerId<=0||string.IsNullOrWhiteSpace(number)||number.Length>34)throw new ArgumentException("Invalid account details");if(type!="Savings"&&type!="Current"&&type!="Deposit")throw new ArgumentException("Invalid account type");using var c=BankDb.Open();using var cmd=new SqlCommand("INSERT INTO Accounts(CustomerId,AccountNumber,AccountType,Balance,Currency,Status) VALUES(@customer,@number,@type,0,'IRR','Active')",c);cmd.Parameters.Add("@customer",SqlDbType.Int).Value=customerId;cmd.Parameters.Add("@number",SqlDbType.NVarChar,34).Value=number;cmd.Parameters.Add("@type",SqlDbType.NVarChar,30).Value=type;cmd.ExecuteNonQuery();}
 public DataTable AuditEvents(){BankSession.RequireAudit();using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT TOP (500) Id,EventType,Details,CreatedAt FROM AuditEvents ORDER BY Id DESC",c);using var da=new SqlDataAdapter(cmd);var dt=new DataTable();da.Fill(dt);return dt;}
 public DataTable TransferTrends(){using var c=BankDb.Open();using var cmd=new SqlCommand("SELECT CAST(CreatedAt AS date) AS Day, COUNT(*) AS TransferCount, SUM(Amount) AS TotalAmount FROM Transfers WHERE CreatedAt>=DATEADD(day,-13,SYSUTCDATETIME()) GROUP BY CAST(CreatedAt AS date) ORDER BY Day",c);using var da=new SqlDataAdapter(cmd);var dt=new DataTable();da.Fill(dt);return dt;}

}
